### ISSUE TITLE
SEC7111: HTTPS security is compromised using the CDN via https 

### ISSUE THREAD

**Issue by pharring** [projectkudu/SiteExtensionUpdater#1]
My Site Extension (like most), runs as HTTPS, so I try to get the auto-updater script from the CDN via https.

``` JS
<script src="https://cdn.siteextensions.net/lib/siteExtensionUpdater/siteExtensionUpdater.1.0.0.min.js"></script>
```

However, it looks like the certificate on that site is invalid.

**Comment by ZainRizvi** [comment]
Good catch.  Unfortunately Azure CDN doesn't support https for custom domain names yet (it's [in progress](https://feedback.azure.com/forums/169397-cdn/suggestions/1332683-allow-https-for-custom-cdn-domain-names)).

If you want to use https then for now you'll want to use the (ugly) non-custom domain name for the cdn:
https://az761500.vo.msecnd.net/lib/siteExtensionUpdater/siteExtensionUpdater.1.0.0.min.js
